### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Frantishechek** [PauloCesar0073/UdemyLoader#1]
Hi!

does not work -

Erro durante a conversão: [WinError 2]

**Comment by PauloCesar0073** [comment]
@Frantishechek  executou como adm, o app para instalar as dependências ? conseguiu instalar a extensão ? 
fico no seu aguardo ;)

**Comment by Frantishechek** [comment]
> @Frantishechek executou como adm, o app para instalar as dependências ? conseguiu instalar a extensão ? fico no seu aguardo ;)

1 - yes, I did it on the second try
2 - yes installed in portable Waterfox

**Comment by Frantishechek** [comment]
o link foi interceptado com sucesso na linha de comando. mas então há um erro

**Comment by PauloCesar0073** [comment]
você poderia verificar se o ffmpeg estar instalado em  seu PATH ? 

cmd : ffmpeg -version

**Comment by Frantishechek** [comment]
ffmpeg configurado
O programa agora está funcionando. Mas existem bugs totais!

1. o roteiro percorre o curso até a metade (aproximadamente), depois para, depois de um tempo continua / é assim que deveria ser?
2. Após concluir o curso, o script continua dando comandos para listagem (trava em loop)
3. na pasta Pasta de vídeos Baixados, apenas um arquivo com tamanho zero aparece e é excluído (novo a cada vez), portanto não há nada lá
4. o programa faz algo continuamente no console, relatando o sucesso das operações, mas nenhum arquivo é criado
5. O programa criou centenas!!! instâncias (cópias de aplicativos) no painel de notificação do Windows, que não podem ser todas desativadas

**Comment by PauloCesar0073** [comment]
Nova versão da extensão: https://addons.mozilla.org/addon/udemyloader/

**Comment by Frantishechek** [comment]
1. listando agora o programa roda sem parar até o final
2. mas no final ainda continua dando falsos positivos da listagem (não consigo parar)
3. na pasta de download de vídeos, como antes, aparece apenas um arquivo de tamanho zero (e não é o primeiro da lista de cursos, mas arbitrário).
4. O sistema no gerenciador de tarefas mostra que não há tráfego na rede
5. O programa continua mostrando algum tipo de contador (tempo) e carrega o sistema. nenhum resultado!
6. o sistema está poluído com mais de 100 instâncias que não podem ser desativadas

**Comment by PauloCesar0073** [comment]
> Muito obrigado por estes feedbacks isso me ajuda muito mesmo a melhorar o App.
> 

Poderia me enviar um print ou fzr um pequeno vídeo(não precisa áudio )do app trabalhando ?

**Comment by Frantishechek** [comment]
Quero tentar fazer download de outros navegadores (Chrome, etc.). Onde posso encontrar extensões para eles?

**Comment by PauloCesar0073** [comment]
Va no diretório https://github.com/PauloCesar0073/UdemyLoader/tree/main/Ative_A_Extenssao

Onde terá as instruções para a instalação.
